# Generated by Django 6.0.3 on 2026-09-05 04:41

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CREATE_SCHOOL', 'Create School'), ('CREATE_SCHOOL_ADMIN', 'Create School Admin'), ('CREATE_TEACHER', 'Create Teacher'), ('CREATE_STUDENT', 'Create Student'), ('GENERATE_SELECT_QUESTIONS', 'Generate / Select Questions'), ('CREATE_PAPER', 'Create Paper'), ('ASSIGN_TEST', 'Assign Test'), ('ATTEMPT_TEST', 'Attempt Test'), ('VIEW_OWN_RESULT', 'View Own Result'), ('VIEW_SCHOOL_WIDE_CONTROLS', 'View School-Wide Controls')], help_text='Identifier for this capability (must match CapabilityName choices).', max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Capability',
                'verbose_name_plural': 'Capabilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this account (for scope enforcement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('school', models.ForeignKey(blank=True, help_text='School this user belongs to. Null → Super Admin (no school boundary).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.school')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_capabilities', to='users.capability')),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who granted this capability; null for bootstrap/system grants.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capabilities_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_capabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Capability',
                'verbose_name_plural': 'User Capabilities',
                'ordering': ['capability__name'],
                'unique_together': {('user', 'capability')},
            },
        ),
    ]
