# Generated by Django 6.0.3 on 2026-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_populate_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='', help_text='Explicit hierarchical role: Super Admin, School Admin, Teacher, Student.', max_length=30),
        ),
    ]
