# Generated by Django 6.0.3 on 2026-09-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='+919876543210', help_text='Indian mobile number with +91 country code and 10 digits.', max_length=15),
        ),
    ]
