# Generated by Django 6.0.3 on 2026-09-10 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_max_students_school_max_teachers_classsection_and_more'),
        ('users', '0005_populate_demo_mobile_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_section',
            field=models.ForeignKey(blank=True, help_text='Class division this student is enrolled in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.classsection'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_subject',
            field=models.CharField(blank=True, default='', help_text='Primary subject taught by this faculty member (e.g. Mathematics).', max_length=100),
        ),
    ]
