# Generated by Django 6.0.3 on 2026-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_class_section_user_primary_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_subject',
            field=models.CharField(blank=True, default='', help_text='Subject specialization or subjects taught by this faculty member (e.g. Mathematics, Science).', max_length=255),
        ),
    ]
