# Generated by Django 6.0.3 on 2026-09-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_primary_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gr_number',
            field=models.CharField(blank=True, default='', help_text='General Register (GR) Number / Student Registration ID.', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, default='', help_text='Class Roll Number where applicable.', max_length=30),
        ),
    ]
