# Generated by Django 6.0.3 on 2026-09-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_gr_number_user_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='name',
            field=models.CharField(choices=[('CREATE_SCHOOL', 'Create School'), ('CREATE_SCHOOL_ADMIN', 'Create School Admin'), ('CREATE_TEACHER', 'Create Teacher'), ('CREATE_STUDENT', 'Create Student'), ('GENERATE_SELECT_QUESTIONS', 'Generate / Select Questions'), ('CREATE_PAPER', 'Create Paper'), ('ASSIGN_TEST', 'Assign Test'), ('ATTEMPT_TEST', 'Attempt Test'), ('VIEW_OWN_RESULT', 'View Own Result'), ('VIEW_SCHOOL_WIDE_CONTROLS', 'View School-Wide Controls'), ('INGEST_GLOBAL_QUESTIONS', 'Ingest Global Questions')], help_text='Identifier for this capability (must match CapabilityName choices).', max_length=60, unique=True),
        ),
    ]
