# Generated by Django 6.0.3 on 2026-09-30 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0004_school_validation_workflow_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('start_page', models.PositiveIntegerField(default=1)),
                ('end_page', models.PositiveIntegerField(default=1)),
                ('summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Extracted Chapter',
                'verbose_name_plural': 'Extracted Chapters',
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Document or textbook title (e.g. 'NCERT Class 10 Mathematics').", max_length=255)),
                ('subject', models.CharField(blank=True, default='', help_text="Academic subject (e.g. 'Mathematics', 'Science', 'Physics').", max_length=100)),
                ('standard', models.PositiveSmallIntegerField(blank=True, help_text='Grade / Standard level (e.g. 8, 9, 10, 11, 12).', null=True)),
                ('board', models.CharField(blank=True, default='NCERT', help_text="Educational board (e.g. 'NCERT', 'CBSE', 'GSEB').", max_length=50)),
                ('document_kind', models.CharField(choices=[('TEXTBOOK', 'Textbook'), ('HANDWRITTEN_NOTES', 'Handwritten Notes'), ('QUESTION_PAPER', 'Question Paper'), ('OTHER', 'Other Material')], db_index=True, default='TEXTBOOK', max_length=30)),
                ('granularity', models.CharField(choices=[('UNKNOWN', 'Unknown / Not Yet Detected'), ('WHOLE_BOOK', 'Whole Book'), ('CHAPTER', 'Single Chapter'), ('TOPIC', 'Single Topic / Notes')], db_index=True, default='UNKNOWN', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing Layout & TOC'), ('EXTRACTING', 'Extracting Structured Content'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('total_pages', models.PositiveIntegerField(default=0, help_text='Total number of pages detected in the uploaded PDF.')),
                ('processed_pages', models.PositiveIntegerField(default=0, help_text='Number of pages successfully parsed and structured.')),
                ('current_stage', models.CharField(blank=True, default='', help_text="Human-readable progress message (e.g. 'Extracting Chapter 2 (Page 45/180)').", max_length=150)),
                ('source_file', models.FileField(blank=True, help_text='Temporary local upload path for processing.', null=True, upload_to='ingestion_raw/%Y/%m/')),
                ('file_size_bytes', models.BigIntegerField(default=0, help_text='Uploaded PDF file size in bytes.')),
                ('google_drive_file_id', models.CharField(blank=True, default='', help_text='Google Drive file ID for cloud backup.', max_length=255)),
                ('google_drive_url', models.URLField(blank=True, default='', help_text='Direct view / download link in Google Drive.', max_length=500)),
                ('error_message', models.TextField(blank=True, default='', help_text='Details of any parsing error if status == FAILED.')),
                ('table_of_contents', models.JSONField(blank=True, default=list, help_text="Detected TOC list: [{'chapter_number': 1, 'title': '...', 'start_page': 1, 'end_page': 25}].")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary extra metadata (language, author, tags, etc.).')),
                ('school', models.ForeignKey(blank=True, help_text='School tenant owning this ingestion task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='schools.school')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User (teacher, admin) who uploaded the document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingestion Job',
                'verbose_name_plural': 'Ingestion Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('layout_type', models.CharField(default='SINGLE_COLUMN', help_text='SINGLE_COLUMN, TWO_COLUMN, HYBRID_COLUMN, COMPLEX_GRID', max_length=50)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('structured_content', models.JSONField(blank=True, default=list, help_text='Array of structured section objects (headings, paragraphs, formulas, diagrams, etc.).')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this page has been reviewed and approved by a human operator.')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='content_ingestion.extractedchapter')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pages', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='content_ingestion.ingestionjob')),
            ],
            options={
                'verbose_name': 'Extracted Page',
                'verbose_name_plural': 'Extracted Pages',
                'ordering': ['page_number'],
                'unique_together': {('job', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='ExtractedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('PARAGRAPH', 'Paragraph / Body Text'), ('FORMULA', 'Mathematical / Chemical Formula'), ('DIAGRAM', 'Diagram / Image with Caption'), ('ACTIVITY', 'Activity / Experiment / Task'), ('SOLVED_EXAMPLE', 'Solved Example'), ('EXERCISE_QUESTION', 'Exercise / Textbook Question'), ('DEFINITION', 'Key Definition / Terminology'), ('SUMMARY', 'Summary / Key Takeaway')], db_index=True, max_length=40)),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(help_text='Clean extracted text with LaTeX embedded.')),
                ('latex_equations', models.JSONField(blank=True, default=list, help_text='List of isolated LaTeX formula strings found in this item.')),
                ('image_path', models.CharField(blank=True, default='', help_text='Local or media path of cropped figure.', max_length=500)),
                ('image_caption', models.TextField(blank=True, default='', help_text='Associated figure/diagram caption.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contextual metadata (column, paragraph_idx, confidence, etc.).')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='content_ingestion.extractedchapter')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content_ingestion.extractedpage')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content_ingestion.ingestionjob')),
            ],
            options={
                'verbose_name': 'Extracted Item',
                'verbose_name_plural': 'Extracted Items',
                'ordering': ['page__page_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='extractedchapter',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content_ingestion.ingestionjob'),
        ),
        migrations.AlterUniqueTogether(
            name='extractedchapter',
            unique_together={('job', 'chapter_number')},
        ),
    ]
