# Generated by Django 6.0.3 on 2026-10-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='classification_confidence',
            field=models.FloatField(blank=True, default=None, help_text='Confidence score (0.0 to 1.0) of document classifier.', null=True),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='classification_evidence',
            field=models.TextField(blank=True, default='', help_text='Diagnostic evidence strings explaining why this document kind was assigned.'),
        ),
        migrations.AlterField(
            model_name='extractedchapter',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='extracteditem',
            name='heading',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='extracteditem',
            name='image_path',
            field=models.TextField(blank=True, default='', help_text='Local or media path of cropped figure.'),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='board',
            field=models.CharField(blank=True, default=None, help_text="Educational board (e.g. 'NCERT', 'CBSE', 'GSEB').", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='document_kind',
            field=models.CharField(blank=True, choices=[('TEXTBOOK', 'Textbook'), ('FULL_BOOK', 'Full Book'), ('SINGLE_CHAPTER', 'Single Chapter'), ('SINGLE_TOPIC', 'Single Topic'), ('WORKSHEET_OR_EXAM', 'Worksheet or Exam'), ('QUESTION_PAPER', 'Question Paper'), ('NOTES', 'Notes'), ('HANDWRITTEN_NOTES', 'Handwritten Notes'), ('NEWSPAPER', 'Newspaper'), ('MAGAZINE', 'Magazine'), ('OTHER', 'Other Material'), ('UNKNOWN', 'Unknown')], db_index=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='standard',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Grade / Standard level (e.g. 8, 9, 10, 11, 12).', null=True),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='subject',
            field=models.CharField(blank=True, default=None, help_text="Academic subject (e.g. 'Mathematics', 'Science', 'Physics').", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ingestionjob',
            name='table_of_contents',
            field=models.JSONField(blank=True, default=list, help_text="Detected TOC list: [{'chapter_number': 1, 'title': '...', 'start_page': 1, 'end_page': 25}].", null=True),
        ),
    ]
