# Generated by Django 6.0.3 on 2026-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0002_ingestionjob_classification_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiResultCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('response_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Gemini Result Cache',
                'verbose_name_plural': 'Gemini Result Caches',
            },
        ),
    ]
