# Generated by Django 6.0.3 on 2026-10-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0003_geminiresultcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteditem',
            name='image_description',
            field=models.TextField(blank=True, default='', help_text='Detailed description or context for the image.'),
        ),
        migrations.AddField(
            model_name='extracteditem',
            name='image_label',
            field=models.CharField(blank=True, default='', help_text='Figure/Diagram label or identifier (e.g. Figure 1.1, चित्र 2.1).', max_length=255),
        ),
    ]
