# Generated by Django 6.0.3 on 2026-10-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ingestion', '0004_extracteditem_image_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteditem',
            name='image_caption',
            field=models.TextField(blank=True, default='', help_text='Associated figure/diagram caption.', null=True),
        ),
        migrations.AlterField(
            model_name='extracteditem',
            name='image_description',
            field=models.TextField(blank=True, default='', help_text='Detailed description or context for the image.', null=True),
        ),
        migrations.AlterField(
            model_name='extracteditem',
            name='image_label',
            field=models.CharField(blank=True, default='', help_text='Figure/Diagram label or identifier (e.g. Figure 1.1, चित्र 2.1).', max_length=255, null=True),
        ),
    ]
