# Generated by Django 6.0.3 on 2026-09-05 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Title of the paper (e.g. 'Class 10 Real Numbers Unit Test').", max_length=255)),
                ('instructions', models.TextField(blank=True, default='', help_text='General instructions displayed to students.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], db_index=True, default='DRAFT', help_text='DRAFT | FINALIZED', max_length=20)),
                ('chapter', models.ForeignKey(help_text='The curriculum chapter this paper covers.', on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='content.chapter')),
                ('created_by', models.ForeignKey(help_text='User who created this paper.', on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, help_text='School this paper belongs to (inherited from creator for scoping).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='schools.school')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_label', models.CharField(help_text='Auto-incremented version label, e.g. "A", "B", "C".', max_length=10)),
                ('question_snapshot', models.JSONField(default=list, help_text='Ordered list of question dicts captured at creation time: [{question_id, question_text, question_type, marks, difficulty, options, correct_answer}].')),
                ('total_marks', models.PositiveIntegerField(default=0, help_text='Stored total marks, computed from question_snapshot at save time.')),
                ('constraints_used', models.JSONField(blank=True, default=dict, help_text='The filters and constraints that produced this version (for traceability).')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], db_index=True, default='DRAFT', help_text='DRAFT | FINALIZED', max_length=20)),
                ('paper', models.ForeignKey(help_text='The parent Paper container.', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='papers.paper')),
            ],
            options={
                'verbose_name': 'Paper Version',
                'verbose_name_plural': 'Paper Versions',
                'ordering': ['paper', 'version_label'],
                'unique_together': {('paper', 'version_label')},
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('PRINT', 'Print'), ('ONLINE', 'Online')], db_index=True, help_text='PRINT | ONLINE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', help_text='DRAFT | ACTIVE | CLOSED', max_length=20)),
                ('available_from', models.DateTimeField(blank=True, help_text='Start of the availability window (optional).', null=True)),
                ('available_until', models.DateTimeField(blank=True, help_text='End of the availability window (optional).', null=True)),
                ('assigned_students', models.ManyToManyField(blank=True, help_text='Students assigned to this test (required for ONLINE mode).', related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user (teacher/admin) who created this delivery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL)),
                ('paper_version', models.ForeignKey(help_text='The specific PaperVersion being delivered.', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='papers.paperversion')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
