# Generated by Django 6.0.3 on 2026-09-10 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
        ('schools', '0002_school_max_students_school_max_teachers_classsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='target_class',
            field=models.ForeignKey(blank=True, help_text='Class section division targeted for this delivery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='schools.classsection'),
        ),
    ]
