# Generated by Django 6.0.3 on 2026-09-11 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_questionvariant_alter_book_options_and_more'),
        ('papers', '0002_delivery_target_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Exam duration in minutes (AC-18).'),
        ),
        migrations.AddField(
            model_name='paper',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Blueprint specifications: subject breakdown, difficulty distribution, section/bucket quotas.'),
        ),
        migrations.AddField(
            model_name='paper',
            name='subjects',
            field=models.JSONField(blank=True, default=list, help_text='List of subjects/books included in multi-subject papers (AC-17).'),
        ),
        migrations.AddField(
            model_name='paper',
            name='total_question_count',
            field=models.PositiveIntegerField(default=0, help_text='Target total question count (AC-18).'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='The curriculum chapter this paper covers (optional for multi-subject papers).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='content.chapter'),
        ),
    ]
