# Generated by Django 6.0.3 on 2026-09-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Short snake_case verb, e.g. "user.created".', max_length=100)),
                ('target_type', models.CharField(db_index=True, help_text='App-label.model-name, e.g. "users.user".', max_length=100)),
                ('target_id', models.CharField(db_index=True, help_text='String PK of the affected object.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary extra context (old/new values, IP, etc.).')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
