# Generated by Django 6.0.3 on 2026-09-10 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='max_students',
            field=models.PositiveIntegerField(default=500, help_text='Maximum student enrollment capacity permitted by Super Admin.'),
        ),
        migrations.AddField(
            model_name='school',
            name='max_teachers',
            field=models.PositiveIntegerField(default=50, help_text='Maximum teacher accounts capacity permitted by Super Admin.'),
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.PositiveSmallIntegerField(help_text='Standard / Grade level (e.g. 8, 9, 10).')),
                ('section', models.CharField(help_text="Division or section letter (e.g. 'A', 'B', 'C', up to 'J').", max_length=5)),
                ('max_students', models.PositiveIntegerField(default=40, help_text='Maximum student capacity allowed in this division (set by School Admin).')),
                ('class_teacher_subject', models.CharField(blank=True, default='General', help_text='Primary subject taught by the Class Teacher (e.g., Mathematics).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Main faculty instructor acting as the Class Teacher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_class', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='School tenant owning this class division.', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school')),
            ],
            options={
                'verbose_name': 'Class Section',
                'verbose_name_plural': 'Class Sections',
                'ordering': ['standard', 'section'],
                'unique_together': {('school', 'standard', 'section')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject name (e.g., Mathematics, Science, English, Social Science).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_section', models.ForeignKey(help_text='Class division receiving instruction.', on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='schools.classsection')),
                ('teacher', models.ForeignKey(help_text='Assigned faculty instructor for this subject.', on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Subject Teacher',
                'verbose_name_plural': 'Class Subject Teachers',
                'ordering': ['subject'],
                'unique_together': {('class_section', 'subject')},
            },
        ),
    ]
