# Generated by Django 6.0.3 on 2026-09-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_max_students_school_max_teachers_classsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='question_bank_enabled',
            field=models.BooleanField(default=False, help_text='Whether Question Bank capability is enabled for this organization by Super Admin.'),
        ),
    ]
