# Generated by Django 6.0.3 on 2026-09-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_question_bank_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='validation_workflow_enabled',
            field=models.BooleanField(default=False, help_text='Controls whether the school uses the DEO -> Validator validation workflow or direct question generation.'),
        ),
    ]
