# Generated by Django 6.0.3 on 2026-09-05 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EVALUATED', 'Evaluated')], db_index=True, default='NOT_STARTED', help_text='NOT_STARTED | IN_PROGRESS | SUBMITTED | EVALUATED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the student initiated the attempt.', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the student submitted the attempt.', null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Computed score awarded so far.', max_digits=6, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum possible marks copied from PaperVersion total_marks.', max_digits=6)),
                ('delivery', models.ForeignKey(help_text='Delivery being sat by the student.', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='papers.delivery')),
                ('student', models.ForeignKey(help_text='Student taking this test.', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
                'ordering': ['-created_at'],
                'unique_together': {('delivery', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.IntegerField(help_text='ID of the question from the snapshot (not live FK).')),
                ('question_snapshot', models.JSONField(help_text='Snapshot copy of that specific question at delivery creation time.')),
                ('student_response', models.TextField(blank=True, default='', help_text="Student response (e.g. choice letter 'A' or text).")),
                ('is_correct', models.BooleanField(blank=True, help_text='True if correct, False if incorrect, null if pending manual review.', null=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, help_text='Marks awarded for this answer.', max_digits=5, null=True)),
                ('attempt', models.ForeignKey(help_text='Parent attempt.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.attempt')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['id'],
                'unique_together': {('attempt', 'question_id')},
            },
        ),
    ]
