# Generated by Django 6.0.3 on 2026-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='proctoring_logs',
            field=models.JSONField(blank=True, default=list, help_text='Detailed audit log of proctoring events during this attempt.'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='warning_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of proctoring warnings (e.g. tab switches, blur) recorded during exam.'),
        ),
    ]
