# Generated by Django 6.0.3 on 2026-09-05 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Full title of the book.', max_length=255)),
                ('subject', models.CharField(help_text='Subject area, e.g. "Mathematics", "Physics".', max_length=100)),
                ('grade', models.CharField(help_text='Grade / level, e.g. "Class 10", "Grade 12".', max_length=50)),
                ('publisher', models.CharField(blank=True, default='', help_text='Publisher name (optional).', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive books are hidden from browsing.')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['subject', 'grade', 'title'],
                'unique_together': {('title', 'subject', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('chapter_order', models.PositiveIntegerField(help_text='1-based ordering of chapters within the book.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.book')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['book', 'chapter_order'],
                'unique_together': {('book', 'chapter_order')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.chapter')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['chapter', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField(help_text='Full text of the question.')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT_ANSWER', 'Short Answer'), ('LONG_ANSWER', 'Long Answer')], db_index=True, help_text='MCQ | SHORT_ANSWER | LONG_ANSWER', max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, help_text='Marks awarded for a correct answer.', max_digits=5)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, help_text='EASY | MEDIUM | HARD', max_length=10)),
                ('learner_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], db_index=True, help_text='BEGINNER | INTERMEDIATE | ADVANCED', max_length=15)),
                ('options', models.JSONField(blank=True, help_text='MCQ answer choices as a dict, e.g. {"A": "...", "B": "...", ...}. Null for non-MCQ questions.', null=True)),
                ('correct_answer', models.TextField(help_text='"A" / "B" / etc. for MCQ; short phrase for SHORT_ANSWER; marking rubric for LONG_ANSWER.')),
                ('source_reference', models.CharField(blank=True, default='', help_text='Page number, section, or exercise reference (optional).', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive questions are excluded from paper-builder queries.')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.topic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['topic', 'difficulty', 'question_type'],
                'indexes': [models.Index(fields=['topic', 'question_type', 'difficulty', 'learner_level'], name='question_filter_idx'), models.Index(fields=['is_active', 'difficulty'], name='question_active_diff_idx')],
            },
        ),
    ]
