# Generated by Django 6.0.3 on 2026-09-11 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('schools', '0003_school_question_bank_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MSQ', 'Multiple Select'), ('ONE_WORD', 'One Word'), ('FILL_IN_THE_BLANKS', 'Fill in the Blanks'), ('MATCH_THE_FOLLOWING', 'Match the Following'), ('DIAGRAM_BASED', 'Diagram Based'), ('COMPREHENSION_BASED', 'Comprehension Based'), ('SHORT_ANSWER', 'Short Answer'), ('LONG_ANSWER', 'Long Answer')], db_index=True, help_text='MCQ | MSQ | ONE_WORD | FILL_IN_THE_BLANKS | MATCH_THE_FOLLOWING | DIAGRAM_BASED | COMPREHENSION_BASED | SHORT_ANSWER | LONG_ANSWER', max_length=30)),
                ('marks', models.DecimalField(decimal_places=2, help_text='Marks for this variant (e.g. 2.00, 3.00, 5.00) (AC-16).', max_digits=5)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], help_text='Must match parent question difficulty (AC-15).', max_length=10)),
                ('question_text', models.TextField(help_text='Full text of the variant question.')),
                ('options', models.JSONField(blank=True, help_text='Options for choice-based questions (dict or list).', null=True)),
                ('correct_answer', models.TextField(help_text='Answer or marking rubric for this variant.')),
                ('explanation', models.TextField(blank=True, default='', help_text='Explanation, hints, or marking guidance for this variant.')),
            ],
            options={
                'verbose_name': 'Question Variant',
                'verbose_name_plural': 'Question Variants',
                'ordering': ['parent_question', 'marks'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['board', 'subject', 'grade', 'title'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='book',
            name='board',
            field=models.CharField(db_index=True, default='CBSE', help_text='Educational board, e.g. "CBSE", "ICSE", "State Board".', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='bank_source',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('ORGANIZATION', 'Organization'), ('TEACHER', 'Teacher')], db_index=True, default='GLOBAL', help_text='GLOBAL | ORGANIZATION | TEACHER (AC-13, AC-14)', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created or ingested this question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Solution explanation, hints, or marking guidance.'),
        ),
        migrations.AddField(
            model_name='question',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Organization owning this question. Null for GLOBAL bank questions (AC-14).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(help_text='"A" / "B" / etc. for MCQ; list/array string for MSQ; short phrase for SHORT_ANSWER; marking rubric for LONG_ANSWER.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='MCQ/MSQ choices as a dict e.g. {"A": "...", "B": "...", ...} or structured items. Null for free-text questions.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MSQ', 'Multiple Select'), ('ONE_WORD', 'One Word'), ('FILL_IN_THE_BLANKS', 'Fill in the Blanks'), ('MATCH_THE_FOLLOWING', 'Match the Following'), ('DIAGRAM_BASED', 'Diagram Based'), ('COMPREHENSION_BASED', 'Comprehension Based'), ('SHORT_ANSWER', 'Short Answer'), ('LONG_ANSWER', 'Long Answer')], db_index=True, help_text='MCQ | MSQ | ONE_WORD | FILL_IN_THE_BLANKS | MATCH_THE_FOLLOWING | DIAGRAM_BASED | COMPREHENSION_BASED | SHORT_ANSWER | LONG_ANSWER', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'subject', 'grade', 'board')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['bank_source', 'school'], name='question_tenant_idx'),
        ),
        migrations.AddField(
            model_name='questionvariant',
            name='parent_question',
            field=models.ForeignKey(help_text='The parent question this variant belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='content.question'),
        ),
    ]
