# Generated by Django 6.0.3 on 2026-09-16 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_questionvariant_alter_book_options_and_more'),
        ('schools', '0004_school_validation_workflow_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionValidationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit for Validation'), ('START_VALIDATION', 'Start Validation'), ('METADATA_UPDATE', 'Update Metadata'), ('SEND_FOR_CORRECTION', 'Send for Correction'), ('RESUBMIT', 'Resubmit for Validation'), ('APPROVE', 'Approve Question'), ('REJECT', 'Reject Question')], db_index=True, max_length=30)),
                ('comment', models.TextField(blank=True, default='', help_text='Validator or DEO comment. Mandatory for SEND_FOR_CORRECTION and REJECT.')),
                ('changed_fields', models.JSONField(blank=True, default=dict, help_text='Stores old and new values for metadata changes: topics, difficulty, marks, variant marks.')),
                ('revision', models.PositiveIntegerField(default=1, help_text='Question revision number at the time of this validation action.')),
            ],
            options={
                'verbose_name': 'Question Validation History',
                'verbose_name_plural': 'Question Validation Histories',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='revision',
            field=models.PositiveIntegerField(default=1, help_text='Revision counter incremented each time question content is corrected and resubmitted.'),
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Multiple topics associated with this question.', related_name='questions_m2m', to='content.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='validation_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Validation'), ('UNDER_VALIDATION', 'Under Validation'), ('CORRECTION_REQUIRED', 'Correction Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', help_text='DRAFT | SUBMITTED | UNDER_VALIDATION | CORRECTION_REQUIRED | APPROVED | REJECTED', max_length=30),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['validation_status', 'school'], name='question_val_status_idx'),
        ),
        migrations.AddField(
            model_name='questionvalidationhistory',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who performed this validation action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionvalidationhistory',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_history', to='content.question'),
        ),
    ]
